import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import multer from 'multer'
import { PDFDocument, StandardFonts, rgb, degrees } from 'pdf-lib'
import fs from 'fs/promises'
import path from 'path'
import archiver from 'archiver'
import crypto from 'crypto'
import helmet from 'helmet'
import rateLimit from 'express-rate-limit'
import sharp from 'sharp'
import bcrypt from 'bcryptjs'
import { spawn } from 'child_process'

import { dockerAvailable, runInDockerSandbox } from './lib/sandbox.js'

import { authenticate, getUsers, getUserByEmail, createUser, signAccessToken, ensureAdminUser } from './lib/auth.js'
import { appendAuditEvent, readAuditLog, verifyAuditLog } from './lib/audit.js'
import { initVault, listDocsForOwner, readDocBytes, readDocMeta, writeDoc, writeDocMeta } from './lib/vault.js'
import { redactPdfByRasterize, sanitizePdfByRasterize } from './lib/sanitize.js'
import { signPdfBytes, verifyPdfBytes } from './lib/signature.js'
import { inspectEmbeddedSignature, signPdfEmbedded } from './lib/embeddedSignature.js'
import { connectDb } from './lib/db.js'
import { validatePdfWithQpdf } from './lib/validate.js'
import { runPdftoppmPng } from './lib/pdftoppm.js'
import { ocrPdfPageWords } from './lib/ocr.js'
import { readPdfGit, writePdfGit, createEmptyGitRepo, appendGitCommit } from './lib/pdfGit.js'
import { computePagePixelHashes } from './lib/pageHashes.js'
import { signGit, verifyGitSignature } from './lib/gitSigning.js'

const app = express()
const PORT = Number(process.env.PORT || 5000)

const DEFAULT_ALLOWED_ORIGINS = [
  'http://localhost:3000',
  'http://localhost:5173'
]

const ALLOWED_ORIGINS = (process.env.CORS_ORIGIN
  ? process.env.CORS_ORIGIN.split(',').map(s => s.trim()).filter(Boolean)
  : DEFAULT_ALLOWED_ORIGINS
)

const UPLOAD_DIR = process.env.UPLOAD_DIR || './uploads'
const VAULT_DIR = process.env.VAULT_DIR || './secure_storage'
const WORK_DIR = process.env.WORK_DIR || path.join(UPLOAD_DIR, 'work')

const MAX_PDF_BYTES = Number(process.env.MAX_PDF_BYTES || 25 * 1024 * 1024) // 25MB
const MAX_IMAGE_BYTES = Number(process.env.MAX_IMAGE_BYTES || 10 * 1024 * 1024) // 10MB
const PDFTOPPM_TIMEOUT_MS = Number(process.env.PDFTOPPM_TIMEOUT_MS || 60_000)
const MAX_SANITIZE_PAGES = Number(process.env.MAX_SANITIZE_PAGES || 50)

const SHARE_SECRET = process.env.SHARE_SECRET || crypto.randomBytes(32).toString('base64')

const isSafeDocId = (id) => typeof id === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)

const signShareToken = ({ docId, expMs }) => {
  const payload = { docId, expMs }
  const payloadB64 = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64url')
  const sig = crypto.createHmac('sha256', SHARE_SECRET).update(payloadB64).digest('base64url')
  return `${payloadB64}.${sig}`
}

const verifyShareToken = (token) => {
  if (typeof token !== 'string') return null
  const [payloadB64, sig] = token.split('.')
  if (!payloadB64 || !sig) return null
  const expected = crypto.createHmac('sha256', SHARE_SECRET).update(payloadB64).digest('base64url')
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null
  const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'))
  if (!payload?.docId || !payload?.expMs) return null
  if (!isSafeDocId(payload.docId)) return null
  if (Date.now() > payload.expMs) return null
  return payload
}

await connectDb().catch((e) => {
  console.warn('[db] MongoDB not connected:', e?.message || e)
})
await ensureAdminUser().catch(() => {})

const vault = await initVault(VAULT_DIR)
await fs.mkdir(WORK_DIR, { recursive: true })

const isSafeStoredFilename = (filename) => {
  // Stored filenames are generated by us: <uuid>.<ext>
  return typeof filename === 'string' && /^[0-9a-fA-F-]{20,}\.(pdf|png|jpg|jpeg)$/i.test(filename)
}

const getStoredFilename = (mimetype) => {
  let ext = 'bin'
  if (mimetype === 'application/pdf') ext = 'pdf'
  if (mimetype === 'image/png') ext = 'png'
  if (mimetype === 'image/jpeg' || mimetype === 'image/jpg') ext = 'jpg'

  const id = crypto.randomUUID()
  return `${id}.${ext}`
}

const ensureUploadDir = async () => {
  await fs.mkdir(UPLOAD_DIR, { recursive: true })
}

const parseJsonField = (raw, fallback = null) => {
  if (raw == null) return fallback
  if (typeof raw !== 'string') return fallback
  try {
    return JSON.parse(raw)
  } catch {
    return fallback
  }
}

// Middleware
app.use(helmet({
  crossOriginResourcePolicy: { policy: 'cross-origin' }
}))

app.use(rateLimit({
  windowMs: 60 * 1000,
  limit: Number(process.env.RATE_LIMIT_PER_MINUTE || 120),
  standardHeaders: true,
  legacyHeaders: false
}))

app.use(cors({
  origin: (origin, cb) => {
    // allow non-browser tools (no Origin header)
    if (!origin) return cb(null, true)
    if (ALLOWED_ORIGINS.includes(origin)) return cb(null, true)
    if (process.env.NODE_ENV !== 'production') {
      try {
        const u = new URL(origin)
        const host = u.hostname
        const isLocal = host === 'localhost' || host === '127.0.0.1'
        const isRfc1918 = host.startsWith('10.') || host.startsWith('192.168.') || /^172\.(1[6-9]|2\d|3[0-1])\./.test(host)
        if (u.protocol === 'http:' && (isLocal || isRfc1918)) return cb(null, true)
      } catch {
        // ignore parse errors
      }
    }
    return cb(new Error('Not allowed by CORS'))
  }
}))

app.use(express.json({ limit: '1mb' }))

// Configure multer for file uploads
const storage = multer.diskStorage({
  destination: async (req, file, cb) => {
    try {
      await ensureUploadDir()
    } catch (err) {
      console.error('Error creating uploads directory:', err)
    }
    cb(null, UPLOAD_DIR)
  },
  filename: (req, file, cb) => {
    cb(null, getStoredFilename(file.mimetype))
  }
})

const upload = multer({ 
  storage,
  limits: {
    fileSize: MAX_PDF_BYTES,
    files: 1
  },
  fileFilter: (req, file, cb) => {
    const mime = String(file?.mimetype || '').toLowerCase()
    const name = String(file?.originalname || '').toLowerCase()
    const looksLikePdf = mime.includes('pdf') || name.endsWith('.pdf')
    if (looksLikePdf) return cb(null, true)
    return cb(new Error('Only PDF files are allowed'))
  }
})

// Multer config for conversion features (accepts PDFs and images)
const conversionUpload = multer({ 
  storage,
  limits: {
    fileSize: Math.max(MAX_PDF_BYTES, MAX_IMAGE_BYTES),
    files: 50
  },
  fileFilter: (req, file, cb) => {
    const allowedTypes = ['application/pdf', 'image/jpeg', 'image/png', 'image/jpg']
    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true)
    } else {
      cb(new Error('Only PDF and image files are allowed'))
    }
  }
})

// Multer config for office conversions (PPT/PPTX)
const officeUpload = multer({
  storage,
  limits: {
    fileSize: Math.max(MAX_PDF_BYTES, 25 * 1024 * 1024),
    files: 1
  },
  fileFilter: (req, file, cb) => {
    const mime = String(file?.mimetype || '').toLowerCase()
    const name = String(file?.originalname || '').toLowerCase()

    const isPpt = name.endsWith('.ppt') || name.endsWith('.pptx')
    const isPptMime = [
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/octet-stream'
    ].includes(mime)

    if (isPpt || isPptMime) return cb(null, true)
    return cb(new Error('Only PPT/PPTX files are allowed'))
  }
})

const runLibreOfficeConvertToPdf = async ({ inputPath, outDir, timeoutMs }) => {
  const candidates = ['libreoffice', 'soffice']

  const tryRun = (cmd) => new Promise((resolve, reject) => {
    const args = [
      '--headless',
      '--nologo',
      '--nofirststartwizard',
      '--norestore',
      '--convert-to', 'pdf',
      '--outdir', outDir,
      inputPath
    ]

    const child = spawn(cmd, args, { shell: false, windowsHide: true, stdio: ['ignore', 'ignore', 'pipe'] })

    let stderr = ''
    child.stderr?.on('data', (d) => {
      stderr += d.toString()
      if (stderr.length > 20_000) stderr = stderr.slice(-20_000)
    })

    const timer = timeoutMs ? setTimeout(() => {
      child.kill('SIGKILL')
      reject(new Error(`${cmd} timed out`))
    }, timeoutMs) : null

    child.on('error', (err) => {
      if (timer) clearTimeout(timer)
      reject(err)
    })

    child.on('close', (code) => {
      if (timer) clearTimeout(timer)
      if (code === 0) return resolve()
      reject(new Error(`${cmd} failed (code ${code}): ${stderr || 'unknown error'}`))
    })
  })

  let lastErr = null
  for (const cmd of candidates) {
    try {
      await tryRun(cmd)
      return
    } catch (e) {
      lastErr = e
      // ENOENT => binary not installed; try next candidate.
      if (e?.code === 'ENOENT') continue
    }
  }

  if (lastErr?.code === 'ENOENT') {
    throw new Error('LibreOffice is not installed (expected `libreoffice` or `soffice`). Install LibreOffice to enable PPT→PDF conversion.')
  }
  throw lastErr || new Error('LibreOffice conversion failed')
}

const runQpdf = async ({ jobDir, args, timeoutMs }) => {
  const useDocker = (process.env.SANDBOX_DOCKER || '1') !== '0'
  const hasDocker = useDocker ? await dockerAvailable() : false

  const runLocal = async () => {
    await new Promise((resolve, reject) => {
      const child = spawn('qpdf', args, { cwd: jobDir, shell: false, windowsHide: true, stdio: ['ignore', 'ignore', 'pipe'] })

      let stderr = ''
      child.stderr?.on('data', (d) => {
        stderr += d.toString()
        if (stderr.length > 20_000) stderr = stderr.slice(-20_000)
      })

      const timer = timeoutMs ? setTimeout(() => {
        child.kill('SIGKILL')
        reject(new Error('qpdf timed out'))
      }, timeoutMs) : null

      child.on('error', (err) => {
        if (timer) clearTimeout(timer)
        reject(err)
      })

      child.on('close', (code) => {
        if (timer) clearTimeout(timer)
        if (code === 0) return resolve()
        reject(new Error(`qpdf failed (code ${code}): ${stderr || 'unknown error'}`))
      })
    })
  }

  if (hasDocker) {
    const image = process.env.SANDBOX_IMAGE || 'secure-pdf-sanitizer:latest'
    try {
      await runInDockerSandbox({
        image,
        workDir: jobDir,
        cmd: 'qpdf',
        args,
        timeoutMs
      })
      return
    } catch {
      await runLocal()
      return
    }
  }

  await runLocal()
}

// Routes
app.get('/', (req, res) => {
  res.json({ message: 'PDF Editor Backend API' })
})

// Auth
app.post('/api/auth/signup', async (req, res) => {
  try {
    const { name, email, password } = req.body || {}
    if (!name || !email || !password) {
      return res.status(400).json({ error: 'name, email and password required' })
    }

    const newUser = await createUser(name, email, password)
    
    // Auto login on signup
    const token = signAccessToken(newUser)
    return res.json({
      token,
      user: { id: newUser.id, name: newUser.name, email: newUser.email, roles: newUser.roles }
    })
  } catch (e) {
    if (e.message === 'User already exists') {
      return res.status(400).json({ error: e.message })
    }
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body || {}
    if (!email || !password) {
      return res.status(400).json({ error: 'email and password required' })
    }

    const user = await getUserByEmail(email)
    if (!user) return res.status(401).json({ error: 'Invalid credentials' })

    const ok = bcrypt.compareSync(String(password), user.passwordHash)
    if (!ok) return res.status(401).json({ error: 'Invalid credentials' })

    const token = signAccessToken(user)
    return res.json({
      token,
      user: { id: user.id, name: user.name, email: user.email, roles: user.roles }
    })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/auth/google', async (req, res) => {
  try {
    const { credential } = req.body || {}
    if (!credential) return res.status(400).json({ error: 'credential required' })

    // Minimal fallback verification using jwt-decode for seamless demo experience
    const jwt = await import('jsonwebtoken')
    const payload = jwt.default.decode(credential)
    if (!payload) throw new Error('Invalid token format')

    const { email, name } = payload
    if (!email) return res.status(400).json({ error: 'Email missing from Google token' })

    let user = await getUserByEmail(email)
    if (!user) {
      const crypto = await import('crypto')
      const randomPassword = crypto.randomBytes(16).toString('hex')
      user = await createUser(name || email.split('@')[0], email, randomPassword)
    }

    const token = signAccessToken(user)
    return res.json({
      token,
      user: { id: user.id, name: user.name, email: user.email, roles: user.roles }
    })
  } catch (e) {
    return res.status(500).json({ error: 'Google auth failed: ' + e.message })
  }
})

app.get('/api/auth/me', authenticate, (req, res) => {
  res.json({ user: req.user })
})

// Documents (secure vault)
app.get('/api/documents', authenticate, async (req, res) => {
  const docs = await listDocsForOwner(vault, req.user.id)
  res.json({ documents: docs })
})

app.post('/api/documents', authenticate, upload.single('pdf'), async (req, res) => {
  let tempPath
  try {
    if (!req.file) return res.status(400).json({ error: 'No PDF file uploaded' })
    tempPath = req.file.path
    const inBytes = await fs.readFile(tempPath)

    // If the PDF already contains TEB Git metadata, preserve it across sanitization.
    const incomingGit = await readPdfGit(inBytes).catch(() => ({ git: null }))

    const validation = await validatePdfWithQpdf({ pdfBytes: inBytes, workDir: WORK_DIR })
    if (!validation.ok) {
      return res.status(400).json({ error: `PDF failed structural validation: ${validation.error}` })
    }

    const { bytes: safeBytes, pageCount } = await sanitizePdfByRasterize({
      pdfBytes: inBytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS,
      maxPages: MAX_SANITIZE_PAGES
    })

    let finalBytes = safeBytes
    if (incomingGit?.git?.tebPdfGit === true) {
      const pageHashes = await computePagePixelHashes({
        pdfBytes: safeBytes,
        workDir: WORK_DIR,
        timeoutMs: PDFTOPPM_TIMEOUT_MS
      })

      const actor = { id: req.user.id, name: req.user.name, email: req.user.email }
      const nextGit = appendGitCommit({
        git: incomingGit.git,
        actor,
        message: 'Import + sanitize',
        actions: [{ type: 'import+sanitize', pageCount }],
        pageHashes
      })
      nextGit.signature = signGit(nextGit)
      finalBytes = await writePdfGit(safeBytes, nextGit)
    }

    const docId = crypto.randomUUID()
    const now = new Date().toISOString()
    const meta = await writeDoc(vault, docId, {
      bytes: finalBytes,
      ownerId: req.user.id,
      originalName: req.file?.originalname || 'Untitled Document',
      createdAt: now,
      updatedAt: now,
      pageCount
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId,
      actor: req.user.id,
      action: 'upload+sanitize',
      details: { pageCount }
    })

    return res.json({ id: meta.id, pageCount: meta.pageCount })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  } finally {
    if (tempPath) await fs.unlink(tempPath).catch(() => {})
  }
})

// Upload an updated version of a document (creates a new docId)
app.post('/api/documents/:id/update', authenticate, upload.single('pdf'), async (req, res) => {
  let tempPath
  try {
    const currentId = req.params.id
    if (!isSafeDocId(currentId)) return res.status(400).json({ error: 'Invalid document id' })
    if (!req.file) return res.status(400).json({ error: 'No PDF file uploaded' })
    tempPath = req.file.path

    const currentMeta = await readDocMeta(vault, currentId)
    if (currentMeta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const inBytes = await fs.readFile(tempPath)
    const validation = await validatePdfWithQpdf({ pdfBytes: inBytes, workDir: WORK_DIR })
    if (!validation.ok) {
      return res.status(400).json({ error: `PDF failed structural validation: ${validation.error}` })
    }
    const { bytes: safeBytes, pageCount } = await sanitizePdfByRasterize({
      pdfBytes: inBytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS,
      maxPages: MAX_SANITIZE_PAGES
    })

    // Preserve/advance embedded PDF Git metadata across sanitization.
    // Sanitization rasterizes the PDF (dropping attachments), so if the *current* version
    // has PDF Git initialized we must re-embed it into the sanitized output.
    let finalBytes = safeBytes
    const gitActions = parseJsonField(req.body?.gitActions, null)
    const gitMessage = typeof req.body?.gitMessage === 'string' ? req.body.gitMessage : null
    const gitInitIfMissing = String(req.body?.gitInitIfMissing || '').toLowerCase() === 'true'

    const { bytes: currentBytes } = await readDocBytes(vault, currentId)
    const { git: existingGit } = await readPdfGit(currentBytes).catch(() => ({ git: null }))
    const actor = { id: req.user.id, name: req.user.name, email: req.user.email }

    // By default: if the document already has PDF Git, keep it alive by appending a commit.
    // Optionally: allow initializing Git during update with gitInitIfMissing=true.
    let git = existingGit
    if (!git && gitInitIfMissing) {
      git = createEmptyGitRepo({ actor, pageCount })
    }

    if (git?.tebPdfGit === true) {
      const pageHashes = await computePagePixelHashes({
        pdfBytes: safeBytes,
        workDir: WORK_DIR,
        timeoutMs: PDFTOPPM_TIMEOUT_MS
      })

      const nextGit = appendGitCommit({
        git,
        actor,
        message: gitMessage || 'Edit PDF',
        actions: Array.isArray(gitActions) ? gitActions : [{ type: 'edit', pageCount }],
        pageHashes
      })
      nextGit.signature = signGit(nextGit)
      finalBytes = await writePdfGit(safeBytes, nextGit)
    }

    const newId = crypto.randomUUID()
    const now = new Date().toISOString()
    
    // We reuse the current meta originalName instead of overriding with "edited.pdf"
    // const currentMeta = await readDocMeta(vault, currentId).catch(() => ({}))
    
    const meta = await writeDoc(vault, newId, {
      bytes: finalBytes,
      ownerId: req.user.id,
      originalName: req.body?.originalName || currentMeta?.originalName || req.file?.originalname || 'Untitled Document',
      createdAt: now,
      updatedAt: now,
      pageCount,
      parentId: currentId
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId: currentId,
      actor: req.user.id,
      action: 'update->newVersion',
      details: { newId }
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId: newId,
      actor: req.user.id,
      action: 'createVersion',
      details: { parentId: currentId, pageCount }
    })

    return res.json({ id: meta.id, pageCount: meta.pageCount, parentId: currentId })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  } finally {
    if (tempPath) await fs.unlink(tempPath).catch(() => {})
  }
})

app.get('/api/documents/:id/git', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const { git } = await readPdfGit(bytes)
    if (!git) return res.json({ enabled: false })

    const sig = verifyGitSignature(git, { trustedPublicKeyPem: process.env.PDF_GIT_TRUSTED_PUBLIC_KEY_PEM || null })
    return res.json({ enabled: true, git, signature: sig })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/documents/:id/git/init', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const { git: existingGit } = await readPdfGit(bytes).catch(() => ({ git: null }))
    if (existingGit?.tebPdfGit === true) {
      return res.status(409).json({ error: 'PDF Git already initialized' })
    }

    const actor = { id: req.user.id, name: req.user.name, email: req.user.email }
    const git = createEmptyGitRepo({ actor, pageCount: meta.pageCount })
    const pageHashes = await computePagePixelHashes({
      pdfBytes: bytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS
    })
    const nextGit = appendGitCommit({
      git,
      actor,
      message: 'Baseline snapshot',
      actions: [{ type: 'baseline', pageCount: meta.pageCount }],
      pageHashes
    })
    nextGit.signature = signGit(nextGit)

    const updatedBytes = await writePdfGit(bytes, nextGit)

    const newId = crypto.randomUUID()
    const now = new Date().toISOString()
    await writeDoc(vault, newId, {
      bytes: updatedBytes,
      ownerId: req.user.id,
      originalName: meta.originalName || 'Untitled Document',
      createdAt: now,
      updatedAt: now,
      pageCount: meta.pageCount,
      parentId: docId
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId: newId,
      actor: req.user.id,
      action: 'git-init',
      details: { parentId: docId }
    })

    return res.json({ id: newId })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/documents/:id/git/verify', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const { git } = await readPdfGit(bytes)
    if (!git?.tebPdfGit) return res.status(404).json({ error: 'No PDF Git metadata found' })

    const sig = verifyGitSignature(git, { trustedPublicKeyPem: process.env.PDF_GIT_TRUSTED_PUBLIC_KEY_PEM || null })

    const head = git?.commits?.[git?.head]
    if (!head) return res.status(400).json({ error: 'Invalid git metadata: missing HEAD commit' })

    const expected = Array.isArray(head.pageHashes) ? head.pageHashes : []
    const actual = await computePagePixelHashes({
      pdfBytes: bytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS
    })

    const modifiedPages = []
    const byPageExpected = new Map(expected.map(e => [e.page, e]))
    for (const a of actual) {
      const e = byPageExpected.get(a.page)
      if (!e || e.digest !== a.digest || e.alg !== a.alg) {
        modifiedPages.push(a.page)
      }
    }

    const ok = modifiedPages.length === 0
    return res.json({
      ok,
      modifiedPages,
      signature: sig,
      head: { id: head.id, ts: head.ts, message: head.message, actor: head.actor }
    })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/documents/:id/download', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="${docId}.pdf"`)
    res.setHeader('Content-Length', String(bytes.length))

    // Don't block the download on audit logging.
    res.once('finish', () => {
      appendAuditEvent({
        auditDir: vault.auditDir,
        docId,
        actor: req.user.id,
        action: 'download',
        details: { bytes: bytes.length }
      }).catch(() => {})
    })

    return res.send(Buffer.from(bytes))
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/documents/:id/share', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const meta = await readDocMeta(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const ttlMs = Number(req.body?.ttlMs || 15 * 60 * 1000) // default 15 minutes
    const expMs = Date.now() + Math.max(60_000, Math.min(ttlMs, 24 * 60 * 60 * 1000))
    const token = signShareToken({ docId, expMs })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId,
      actor: req.user.id,
      action: 'share',
      details: { expMs }
    })

    return res.json({
      token,
      url: `/api/share/${token}`,
      expiresAt: new Date(expMs).toISOString()
    })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/share/:token', async (req, res) => {
  try {
    const payload = verifyShareToken(req.params.token)
    if (!payload) return res.status(401).json({ error: 'Invalid or expired share token' })
    const { meta, bytes } = await readDocBytes(vault, payload.docId)

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="${payload.docId}.pdf"`)
    res.setHeader('Content-Length', String(bytes.length))

    res.once('finish', () => {
      appendAuditEvent({
        auditDir: vault.auditDir,
        docId: payload.docId,
        actor: 'share-token',
        action: 'download',
        details: { ownerId: meta.ownerId }
      }).catch(() => {})
    })

    return res.send(Buffer.from(bytes))
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/documents/:id/sign', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const sig = signPdfBytes(bytes)
    const nextMeta = { ...meta, signature: sig, updatedAt: new Date().toISOString() }
    await writeDocMeta(vault, docId, nextMeta)

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId,
      actor: req.user.id,
      action: 'sign',
      details: { digest: sig.digest }
    })

    return res.json({ signature: sig })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/documents/:id/sign-embedded', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const p12Path = process.env.PDF_SIGN_P12_PATH
    const passphrase = process.env.PDF_SIGN_P12_PASSPHRASE
    if (!p12Path) {
      return res.status(501).json({
        error: 'Embedded signing not configured (set PDF_SIGN_P12_PATH and PDF_SIGN_P12_PASSPHRASE)'
      })
    }

    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const p12Buffer = await fs.readFile(p12Path)
    const signedBytes = await signPdfEmbedded({
      pdfBytes: bytes,
      p12Buffer,
      passphrase
    })

    // Store as a new version (signing should be the last step).
    const newId = crypto.randomUUID()
    const now = new Date().toISOString()
    await writeDoc(vault, newId, {
      bytes: signedBytes,
      ownerId: req.user.id,
      originalName: meta.originalName || 'Untitled Document',
      createdAt: now,
      updatedAt: now,
      pageCount: meta.pageCount,
      parentId: docId,
      embeddedSignature: true
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId: newId,
      actor: req.user.id,
      action: 'sign-embedded',
      details: { parentId: docId }
    })

    return res.json({ id: newId })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/documents/:id/inspect-embedded-signature', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })
    return res.json({ inspection: inspectEmbeddedSignature(bytes) })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/documents/:id/verify', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const { meta, bytes } = await readDocBytes(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const result = verifyPdfBytes(bytes, meta.signature)
    return res.json({ result })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.get('/api/documents/:id/audit', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })
    const meta = await readDocMeta(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })
    const entries = await readAuditLog({ auditDir: vault.auditDir, docId, limit: 500 })
    const verification = await verifyAuditLog({ auditDir: vault.auditDir, docId })
    return res.json({ entries, verification })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

app.post('/api/documents/:id/redact', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const meta = await readDocMeta(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const redactions = Array.isArray(req.body?.redactions) ? req.body.redactions : []
    const byPage = {}
    for (const r of redactions) {
      const page = Number(r?.page)
      if (!Number.isFinite(page) || page < 1 || page > MAX_SANITIZE_PAGES) continue
      const rects = Array.isArray(r?.rects) ? r.rects : []
      byPage[page] = rects
        .filter(x => x && [x.x, x.y, x.width, x.height].every(Number.isFinite))
        .map(x => ({
          x: Math.max(0, Math.min(1, x.x)),
          y: Math.max(0, Math.min(1, x.y)),
          width: Math.max(0, Math.min(1, x.width)),
          height: Math.max(0, Math.min(1, x.height))
        }))
    }

    const { bytes } = await readDocBytes(vault, docId)
    const validation = await validatePdfWithQpdf({ pdfBytes: bytes, workDir: WORK_DIR })
    if (!validation.ok) {
      return res.status(400).json({ error: `PDF failed structural validation: ${validation.error}` })
    }
    const { bytes: redactedBytes, pageCount } = await redactPdfByRasterize({
      pdfBytes: bytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS,
      maxPages: MAX_SANITIZE_PAGES,
      redactionsByPage: byPage
    })

    const newId = crypto.randomUUID()
    const now = new Date().toISOString()
    const newMeta = await writeDoc(vault, newId, {
      bytes: redactedBytes,
      ownerId: req.user.id,
      originalName: meta.originalName || 'Untitled Document',
      createdAt: now,
      updatedAt: now,
      pageCount,
      parentId: docId
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId,
      actor: req.user.id,
      action: 'redact->newVersion',
      details: { newId, count: redactions.length }
    })

    await appendAuditEvent({
      auditDir: vault.auditDir,
      docId: newId,
      actor: req.user.id,
      action: 'createRedactedVersion',
      details: { parentId: docId, pageCount }
    })

    return res.json({ id: newMeta.id, pageCount: newMeta.pageCount, parentId: docId })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
})

// OCR for rasterized/sanitized PDFs (returns word boxes for building a selectable text layer)
app.get('/api/documents/:id/ocr', authenticate, async (req, res) => {
  try {
    const docId = req.params.id
    if (!isSafeDocId(docId)) return res.status(400).json({ error: 'Invalid document id' })

    const meta = await readDocMeta(vault, docId)
    if (meta.ownerId !== req.user.id) return res.status(403).json({ error: 'Forbidden' })

    const page = Number(req.query?.page || 1)
    if (!Number.isFinite(page) || page < 1 || page > MAX_SANITIZE_PAGES) {
      return res.status(400).json({ error: 'Invalid page' })
    }

    const dpiRaw = Number(req.query?.dpi || process.env.OCR_DPI || 200)
    const dpi = Math.max(72, Math.min(400, Number.isFinite(dpiRaw) ? dpiRaw : 200))

    const langRaw = typeof req.query?.lang === 'string' ? req.query.lang : (process.env.OCR_LANG || 'eng')
    const lang = (/^[a-zA-Z0-9_+]{1,32}$/.test(langRaw) ? langRaw : 'eng')

    const { bytes } = await readDocBytes(vault, docId)
    const validation = await validatePdfWithQpdf({ pdfBytes: bytes, workDir: WORK_DIR })
    if (!validation.ok) {
      return res.status(400).json({ error: `PDF failed structural validation: ${validation.error}` })
    }

    const result = await ocrPdfPageWords({
      pdfBytes: bytes,
      workDir: WORK_DIR,
      timeoutMs: PDFTOPPM_TIMEOUT_MS,
      page,
      dpi,
      lang
    })

    return res.json(result)
  } catch (e) {
    if (e?.code === 'ENOENT') {
      return res.status(500).json({
        error: 'OCR requires the `tesseract` binary. Install `tesseract-ocr` (and language packs) or set TESSERACT_CMD.'
      })
    }
    const msg = String(e?.message || '')
    if (msg.includes('Unsupported state or unable to authenticate data')) {
      return res.status(500).json({
        error: 'Failed to decrypt stored document bytes. This usually means `MASTER_KEY` changed between runs. Set a stable MASTER_KEY and re-upload the PDF (old encrypted docs cannot be OCR’d without the original key).'
      })
    }
    return res.status(500).json({ error: e.message })
  }
})

// Upload PDF
app.post('/api/upload', authenticate, upload.single('pdf'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' })
    }
    
    res.json({
      message: 'File uploaded successfully',
      filename: req.file.filename,
      path: req.file.path
    })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})

// Get PDF info
app.get('/api/pdf/:filename', authenticate, async (req, res) => {
  try {
    const filename = req.params.filename
    if (!isSafeStoredFilename(filename)) {
      return res.status(400).json({ error: 'Invalid filename' })
    }
    const filePath = path.join(UPLOAD_DIR, filename)
    const pdfBytes = await fs.readFile(filePath)
    const pdfDoc = await PDFDocument.load(pdfBytes)
    
    res.json({
      pages: pdfDoc.getPageCount(),
      title: pdfDoc.getTitle() || 'Untitled'
    })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})

// Delete uploaded file
app.delete('/api/pdf/:filename', authenticate, async (req, res) => {
  try {
    const filename = req.params.filename
    if (!isSafeStoredFilename(filename)) {
      return res.status(400).json({ error: 'Invalid filename' })
    }
    const filePath = path.join(UPLOAD_DIR, filename)
    await fs.unlink(filePath)
    res.json({ message: 'File deleted successfully' })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})

// PDF to Images conversion
app.post('/api/pdf-to-images', authenticate, conversionUpload.single('pdf'), async (req, res) => {
  let tempFiles = []
  let outputDir = null
  
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No PDF file uploaded' })
    }

    const pdfPath = req.file.path
    tempFiles.push(pdfPath)
    
    // Create temporary output directory
    outputDir = path.join(UPLOAD_DIR, `temp-${crypto.randomUUID()}`)
    await fs.mkdir(outputDir, { recursive: true })
    
    // Use pdftoppm (part of poppler-utils) to convert PDF to PNG images
    const outputPrefix = path.join(outputDir, 'page')

    await runPdftoppmPng({
      pdfPath,
      outputPrefix,
      timeoutMs: PDFTOPPM_TIMEOUT_MS
    })

    // Read generated image files
    const files = await fs.readdir(outputDir)
    const imageFiles = files.filter(f => f.endsWith('.png')).sort()

    if (imageFiles.length === 0) {
      throw new Error('No images were generated from the PDF')
    }

    // Create a zip file
    const archive = archiver('zip', { zlib: { level: 9 } })
    
    res.attachment('images.zip')
    res.setHeader('Content-Type', 'application/zip')
    
    archive.pipe(res)

    // Add each image to the zip
    for (let i = 0; i < imageFiles.length; i++) {
      const imagePath = path.join(outputDir, imageFiles[i])
      const imageBuffer = await fs.readFile(imagePath)
      const filename = `page-${i + 1}.png`
      archive.append(imageBuffer, { name: filename })
    }

    await archive.finalize()

    // Clean up files after a delay
    setTimeout(async () => {
      try {
        if (outputDir) {
          await fs.rm(outputDir, { recursive: true, force: true })
        }
        for (const file of tempFiles) {
          await fs.unlink(file).catch(() => {})
        }
      } catch (err) {
        console.error('Error deleting temp files:', err)
      }
    }, 2000)

  } catch (error) {
    console.error('Error converting PDF to images:', error)
    
    // Clean up files on error
    try {
      if (outputDir) {
        await fs.rm(outputDir, { recursive: true, force: true }).catch(() => {})
      }
      
      for (const file of tempFiles) {
        await fs.unlink(file).catch(() => {})
      }
    } catch (cleanupErr) {
      console.error('Error during cleanup:', cleanupErr)
    }
    
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to convert PDF to images: ' + error.message })
    }
  }
})

// Images to PDF conversion
app.post('/api/images-to-pdf', authenticate, conversionUpload.array('images', 50), async (req, res) => {
  let tempFiles = []
  
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ error: 'No image files uploaded' })
    }

    tempFiles = req.files.map(f => f.path)

    // Create a new PDF document
    const pdfDoc = await PDFDocument.create()

    // Add each image to the PDF
    for (const file of req.files) {
      try {
        // Use sharp to read and normalize the image
        const imageBuffer = await sharp(file.path)
          .toFormat('png')
          .toBuffer()
        
        // Embed the normalized PNG image
        const image = await pdfDoc.embedPng(imageBuffer)
        const { width, height } = image
        
        // Create a page with the same dimensions as the image
        const page = pdfDoc.addPage([width, height])
        
        // Draw the image to fill the entire page
        page.drawImage(image, {
          x: 0,
          y: 0,
          width: width,
          height: height,
        })
      } catch (imageError) {
        console.error(`Error processing image ${file.originalname}:`, imageError)
        // Continue with other images instead of failing completely
      }
    }

    // Check if any pages were added
    if (pdfDoc.getPageCount() === 0) {
      throw new Error('No valid images could be processed')
    }

    // Save the PDF
    const pdfBytes = await pdfDoc.save()

    // Send the PDF
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=converted.pdf')
    res.send(Buffer.from(pdfBytes))

    // Clean up uploaded image files after sending
    setTimeout(async () => {
      for (const file of tempFiles) {
        try {
          await fs.unlink(file)
        } catch (err) {
          console.error('Error deleting temp file:', err)
        }
      }
    }, 1000)

  } catch (error) {
    console.error('Error converting images to PDF:', error)
    
    // Clean up files on error
    for (const file of tempFiles) {
      try {
        await fs.unlink(file)
      } catch (err) {
        console.error('Error deleting temp file:', err)
      }
    }
    
    res.status(500).json({ error: 'Failed to convert images to PDF: ' + error.message })
  }
})

// Merge PDFs
app.post('/api/merge-pdfs', authenticate, conversionUpload.array('pdfs', 20), async (req, res) => {
  let tempFiles = []

  try {
    if (!req.files || req.files.length < 2) {
      return res.status(400).json({ error: 'Upload at least 2 PDF files to merge' })
    }

    const pdfFiles = req.files.filter(f => {
      const name = String(f?.originalname || '').toLowerCase()
      const mime = String(f?.mimetype || '').toLowerCase()
      return mime.includes('pdf') || name.endsWith('.pdf')
    })

    if (pdfFiles.length < 2) {
      return res.status(400).json({ error: 'Only PDF files are allowed for merging' })
    }

    tempFiles = pdfFiles.map(f => f.path)

    const merged = await PDFDocument.create()
    for (const file of pdfFiles) {
      const bytes = await fs.readFile(file.path)
      const src = await PDFDocument.load(bytes, { ignoreEncryption: true })
      const copied = await merged.copyPages(src, src.getPageIndices())
      copied.forEach(p => merged.addPage(p))
    }

    const mergedBytes = await merged.save()
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=merged.pdf')
    res.send(Buffer.from(mergedBytes))

    setTimeout(async () => {
      for (const file of tempFiles) {
        await fs.unlink(file).catch(() => {})
      }
    }, 1000)
  } catch (error) {
    console.error('Error merging PDFs:', error)
    for (const file of tempFiles) {
      await fs.unlink(file).catch(() => {})
    }
    res.status(500).json({ error: 'Failed to merge PDFs: ' + (error?.message || String(error)) })
  }
})

// PPT/PPTX to PDF conversion (requires LibreOffice/soffice installed)
app.post('/api/ppt-to-pdf', authenticate, officeUpload.single('ppt'), async (req, res) => {
  let tempFiles = []
  let outputDir = null

  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No PPT/PPTX file uploaded' })
    }

    const inputPath = req.file.path
    tempFiles.push(inputPath)

    outputDir = path.join(UPLOAD_DIR, `temp-${crypto.randomUUID()}`)
    await fs.mkdir(outputDir, { recursive: true })

    await runLibreOfficeConvertToPdf({
      inputPath,
      outDir: outputDir,
      timeoutMs: Number(process.env.PPTTOPDF_TIMEOUT_MS || 120_000)
    })

    const outFiles = await fs.readdir(outputDir)
    const pdfCandidates = outFiles.filter(f => f.toLowerCase().endsWith('.pdf'))
    if (pdfCandidates.length === 0) {
      throw new Error('No PDF was generated from the PPT/PPTX')
    }

    // Pick the newest PDF if there are multiple.
    const pdfWithStats = await Promise.all(pdfCandidates.map(async (f) => {
      const p = path.join(outputDir, f)
      const st = await fs.stat(p)
      return { f, p, mtimeMs: st.mtimeMs }
    }))
    pdfWithStats.sort((a, b) => b.mtimeMs - a.mtimeMs)
    const outPdfPath = pdfWithStats[0].p

    const pdfBytes = await fs.readFile(outPdfPath)
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=converted.pdf')
    res.send(Buffer.from(pdfBytes))

    setTimeout(async () => {
      if (outputDir) await fs.rm(outputDir, { recursive: true, force: true }).catch(() => {})
      for (const file of tempFiles) await fs.unlink(file).catch(() => {})
    }, 1500)
  } catch (error) {
    console.error('Error converting PPT to PDF:', error)
    if (outputDir) await fs.rm(outputDir, { recursive: true, force: true }).catch(() => {})
    for (const file of tempFiles) await fs.unlink(file).catch(() => {})
    res.status(500).json({ error: 'Failed to convert PPT to PDF: ' + (error?.message || String(error)) })
  }
})

// Lock PDF (encrypt)
app.post('/api/lock-pdf', authenticate, conversionUpload.single('pdf'), async (req, res) => {
  let tempFiles = []
  let jobDir = null

  try {
    const password = String(req.body?.password || '').trim()
    if (!req.file) return res.status(400).json({ error: 'No PDF file uploaded' })
    if (!password) return res.status(400).json({ error: 'Password is required' })

    const pdfPath = req.file.path
    tempFiles.push(pdfPath)

    jobDir = path.join(WORK_DIR, `qpdf-${crypto.randomUUID()}`)
    await fs.mkdir(jobDir, { recursive: true })
    const inputPath = path.join(jobDir, 'input.pdf')
    const outputPath = path.join(jobDir, 'output.pdf')
    await fs.writeFile(inputPath, await fs.readFile(pdfPath))

    const ownerPassword = crypto.randomBytes(24).toString('base64url')
    await runQpdf({
      jobDir,
      args: ['--encrypt', password, ownerPassword, '256', '--', 'input.pdf', 'output.pdf'],
      timeoutMs: Number(process.env.QPDF_TIMEOUT_MS || 30_000)
    })

    const lockedBytes = await fs.readFile(outputPath)
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=locked.pdf')
    res.send(Buffer.from(lockedBytes))

    setTimeout(async () => {
      if (jobDir) await fs.rm(jobDir, { recursive: true, force: true }).catch(() => {})
      for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    }, 1500)
  } catch (error) {
    const isMissingBinary = error?.code === 'ENOENT' || /qpdf\s+not found|ENOENT/.test(String(error?.message || ''))
    if (jobDir) await fs.rm(jobDir, { recursive: true, force: true }).catch(() => {})
    for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    res.status(500).json({
      error: isMissingBinary
        ? 'qpdf is not installed; cannot lock PDFs. Install qpdf (recommended) or enable the Docker sandbox image.'
        : ('Failed to lock PDF: ' + (error?.message || String(error)))
    })
  }
})

// Unlock PDF (decrypt)
app.post('/api/unlock-pdf', authenticate, conversionUpload.single('pdf'), async (req, res) => {
  let tempFiles = []
  let jobDir = null

  try {
    const password = String(req.body?.password || '').trim()
    if (!req.file) return res.status(400).json({ error: 'No PDF file uploaded' })
    if (!password) return res.status(400).json({ error: 'Password is required' })

    const pdfPath = req.file.path
    tempFiles.push(pdfPath)

    jobDir = path.join(WORK_DIR, `qpdf-${crypto.randomUUID()}`)
    await fs.mkdir(jobDir, { recursive: true })
    const inputPath = path.join(jobDir, 'input.pdf')
    const outputPath = path.join(jobDir, 'output.pdf')
    await fs.writeFile(inputPath, await fs.readFile(pdfPath))

    await runQpdf({
      jobDir,
      args: [`--password=${password}`, '--decrypt', '--', 'input.pdf', 'output.pdf'],
      timeoutMs: Number(process.env.QPDF_TIMEOUT_MS || 30_000)
    })

    const unlockedBytes = await fs.readFile(outputPath)
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=unlocked.pdf')
    res.send(Buffer.from(unlockedBytes))

    setTimeout(async () => {
      if (jobDir) await fs.rm(jobDir, { recursive: true, force: true }).catch(() => {})
      for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    }, 1500)
  } catch (error) {
    const isMissingBinary = error?.code === 'ENOENT' || /qpdf\s+not found|ENOENT/.test(String(error?.message || ''))
    if (jobDir) await fs.rm(jobDir, { recursive: true, force: true }).catch(() => {})
    for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    res.status(500).json({
      error: isMissingBinary
        ? 'qpdf is not installed; cannot unlock PDFs. Install qpdf (recommended) or enable the Docker sandbox image.'
        : ('Failed to unlock PDF: ' + (error?.message || String(error)))
    })
  }
})

// Watermark PDF (simple text watermark)
app.post('/api/watermark-pdf', authenticate, conversionUpload.single('pdf'), async (req, res) => {
  let tempFiles = []
  try {
    const text = String(req.body?.text || 'CONFIDENTIAL').trim() || 'CONFIDENTIAL'
    if (!req.file) return res.status(400).json({ error: 'No PDF file uploaded' })

    const pdfPath = req.file.path
    tempFiles.push(pdfPath)
    const pdfBytes = await fs.readFile(pdfPath)

    const pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true })
    const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    const pages = pdfDoc.getPages()
    for (const page of pages) {
      const { width, height } = page.getSize()

      // Small repeated watermark tiled across the page.
      const size = Math.max(12, Math.min(20, Math.floor(Math.min(width, height) / 45)))
      const textWidth = font.widthOfTextAtSize(text, size)
      const stepX = Math.max(120, textWidth + 90)
      const stepY = Math.max(90, size * 6)

      const startX = -width
      const endX = width * 2
      const startY = -height
      const endY = height * 2

      for (let y = startY; y <= endY; y += stepY) {
        for (let x = startX; x <= endX; x += stepX) {
          page.drawText(text, {
            x,
            y,
            size,
            font,
            color: rgb(0.7, 0.7, 0.7),
            rotate: degrees(35),
            opacity: 0.16
          })
        }
      }
    }

    const outBytes = await pdfDoc.save()
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=watermarked.pdf')
    res.send(Buffer.from(outBytes))

    setTimeout(async () => {
      for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    }, 1000)
  } catch (error) {
    for (const f of tempFiles) await fs.unlink(f).catch(() => {})
    res.status(500).json({ error: 'Failed to watermark PDF: ' + (error?.message || String(error)) })
  }
})

const server = app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`)
})

server.on('error', (err) => {
  if (err?.code === 'EADDRINUSE') {
    // eslint-disable-next-line no-console
    console.error(`[server] Port ${PORT} is already in use. Stop the other process or start with PORT=${PORT + 1}.`)
    process.exit(1)
  }
  throw err
})
